### ISSUE TITLE
Up for grabs?

### ISSUE THREAD

**Issue by pizycki** [bartsokol/Monacs#3]
If you have anything laying and waiting to be done, but has lower priority or can be processed on its own, feel free to share it with us! :)

Really looking forward to see this project becoming more popular, even if it's yet in early stage of development.

It would be awesome if such tasks be marked with proper tag. http://up-for-grabs.net/

**Comment by bartsokol** [comment]
That's a great idea! I've added the `up-for-grabs` label, and will think of potential enhancements people can help with.  Also testing and providing feedback would be very welcome! :)
